디자인 시스템 - Shadow
carpenstreet/carpenstreet-design-system pull request #21
Opened 2024-03-12 04:21 UTC by add0215

# Issue ticket ID

_해당 PR이 연결된 이슈 티켓의 ID를 적어주세요. (ex. PRDT-1399)_  
_이슈 URL을 복사해 붙여넣어도 괜찮습니다._

PRDT-2136

2024-03-14 06:20 UTC, flynn0909 commented
다른 이야기긴 한데, 이 shadow를 잘 쓰려면 어쩔 수 없이 사용처에서 MUI와 emotion을 써줘야겠네요?

2024-03-14 06:20 UTC, flynn0909 requested changes

2024-03-14 06:46 UTC, add0215 commented
넵 useTheme로 theme.shadows를 가져올 수 있긴 하지만, 잘 쓰려면 플린님 말씀대로 사용처에서 MUI를 써야 할 것 같습니다.

2024-03-14 06:46 UTC, add0215 commented on src/shared/settings/Shadows.ts
> +export const Shadows = [
수정 완료되었습니다!

2024-03-14 06:46 UTC, add0215 commented on src/shared/settings/Shadows.ts
> +import { Shadows as ShadowsType } from '@mui/material/styles/shadows';
넵 수정 완료되었습니다!

2024-03-15 05:37 UTC, flynn0909 approved these changes

2024-03-15 05:39 UTC, merged