디자인 시스템 - Grid
carpenstreet/carpenstreet-design-system pull request #23
Opened 2024-03-13 07:20 UTC by add0215

# Issue ticket ID

_해당 PR이 연결된 이슈 티켓의 ID를 적어주세요. (ex. PRDT-1399)_  
_이슈 URL을 복사해 붙여넣어도 괜찮습니다._

PRDT-2135

# Description

## 요약

_이번 PR의 요약을 적어주세요. 3줄 이내 작성을 권장합니다._
- Mui의 Grid 컴포넌트를 사용하여 Container, Item으로 구분하고 2개의 컴포넌트를 export 하였습니다.
- breakpoint를 추가하였고 desktop, mobile이 적용되어 있습니다.

2024-03-14 06:33 UTC, flynn0909 commented
애드님 깃헙 아이디가 섞여 들어왔어요
rebase -i로 author 수정해서 포스 푸시해주세요~

2024-03-14 06:45 UTC, flynn0909 requested changes

2024-03-14 06:45 UTC, flynn0909 commented on src/components/Grid/Grid.tsx
> +};
제안/논의)
`GridContainer`랑 `GridItem`을 나눠서 써야할 이유가 있을까요?

아래처럼 MUI랑 비슷하게 그대로 쓸 수도 있을 것 같아서요, 어떻게 생각하시나요?

```ts
export default function Grid(props: GridProps) {
  const { children, ...rest } = props;
  const { sx, container } = rest;

  const containerProps = {
    columns: { mobile: 4, desktop: 12 },
    spacing: 12,
    sx: {
      maxWidth: '1360px',
      padding: {
        mobile: '0 16px',
        desktop: '0 40px',
      },
      ...sx,
    },
  };

  return (
    <MUIGrid {...rest} {...(container && containerProps)}>
      {children}
    </MUIGrid>
  );
}
```

2024-03-14 06:45 UTC, flynn0909 commented on src/components/Grid/Grid.stories.tsx
> +            <Paper
수정요청) Paper에 숫자를 표시해주는게 좋을 것 같아요

스토리북에서 direction을 수정했을 때 이게 바뀐 건지 안 바뀐 건지 분간을 못하겠어요

2024-03-14 06:45 UTC, flynn0909 commented on src/components/Grid/Grid.stories.tsx
> +            <Paper
뭔가 300px 높이인 점도 좀.. 그 스토리북에서 확인하기 편하지가 않네요 ㅋㅋㅋ row일 땐 너무 위아래로 길고 column일 땐 너무 두꺼워요...

2024-03-14 06:45 UTC, flynn0909 commented on src/components/Grid/Grid.types.ts
> +  direction?: GridDirection;
질문) GridProps에도 direction이 존재하는데, `Pick<GridProps, 'sx' | 'children' | 'direction'>` 대신 이렇게 따로 `import`해오신 이유가 있을까요?

2024-03-14 08:09 UTC, add0215 commented on src/components/Grid/Grid.types.ts
> +  direction?: GridDirection;
앗 따로 import할 이유가 없고 Mui의 GridProps를 그대로 사용해도 괜찮을 것 같아요..! 수정하겠습니다!

2024-03-14 08:10 UTC, add0215 commented on src/components/Grid/Grid.stories.tsx
> +            <Paper
그쵸.. 근데 사실 grid에서 direction을 사용할 일이 많이 없을 것 같아서 storybook에서 표시되는 prop에서 빼고 Paper에 숫자 표시 및 세로 간격 조정하겠습니다!

2024-03-14 09:13 UTC, add0215 commented on src/components/Grid/Grid.tsx
> +};
굳이 2개의 컴포넌트로 나누지 않아도 괜찮을 것 같아요! 플린님이 작성해주신 코드 참고하는게 더 깔끔한 것 같다고 생각되어 수정했습니다!

2024-03-15 05:36 UTC, flynn0909 requested changes

2024-03-15 05:36 UTC, flynn0909 commented on src/components/Grid/Grid.mdx
> +# Grid
MDX의 설명만 좀 수정해주시면 될 것 같아요!

2024-03-15 05:53 UTC, add0215 commented on src/components/Grid/Grid.mdx
> +# Grid
수정 완료입니다!

2024-03-15 05:55 UTC, flynn0909 approved these changes

2024-03-15 06:08 UTC, merged