Menu, MenuItem 컴포넌트 구현
carpenstreet/carpenstreet-design-system pull request #52
Opened 2024-04-04 07:47 UTC by add0215

# Issue ticket ID

_해당 PR이 연결된 이슈 티켓의 ID를 적어주세요. (ex. PRDT-1399)_  
_이슈 URL을 복사해 붙여넣어도 괜찮습니다._

PRDT-2151

# CheckList

***Reviewr는 아래 체크리스트를 확인해주세요***

(PR 작성자는 체크리스트를 수정하지 마세요)

- [ ] `ooo.stories.ts` 파일에 `title`이 제대로 설정되어 있는가?
- [ ] `ooo.tsx` 파일이 `export default function`을 사용하고 있는가?
- [ ] `ooo.types.ts` 파일에서 MUI type을 적당한 곳에서 잘 import해오고 있는가?
- [ ] `ooo.mdx` 파일에서 `<Controls />`의 `include` prop이 잘 설정되어 있는가?
- [ ] 변경사항 전반적으로 import문을 `index.ts`가 아닌 정확한 파일에서 import하고 있는가?

# Description

## 요약

_이번 PR의 요약을 적어주세요. 3줄 이내 작성을 권장합니다._
- 디자인시스템 피그마의 Menu, MenuItem 컴포넌트를 구현했습니다.
- MUI의 Menu 기본 너비는 MenuItem 기준으로 잡히고, 너비를 설정하는 다른 옵션이 없어서 fullWidth와 width prop을 추가하였습니다.
- width는 고정 너비 fullWidth는 Menu의 anchor Element의 너비

# Reference

_참고문서, 참고링크 등을 적어주세요._

2024-04-04 08:51 UTC, flynn0909 commented
`src/index.ts` 에서 export 필요

2024-04-04 09:03 UTC, flynn0909 requested changes

2024-04-04 09:18 UTC, add0215 commented on src/components/Menu/Menu.stories.tsx
> +      marginTop: '8px',
수정 완료입니닷

2024-04-04 10:07 UTC, add0215 commented on src/shared/settings/menuItem/menuItem.ts
> +      '&.Mui-selected': {
수정되었습니다!

2024-04-04 10:08 UTC, add0215 commented on src/components/Menu/Menu.tsx
> +      ...(width !== null && width !== undefined && { width }),
수정 완료되었습니다!

2024-04-05 00:55 UTC, flynn0909 approved these changes

2024-04-05 01:34 UTC, merged