Divider 컴포넌트 구현
carpenstreet/carpenstreet-design-system pull request #60
Opened 2024-04-12 09:58 UTC by add0215

# Issue ticket ID

_해당 PR이 연결된 이슈 티켓의 ID를 적어주세요. (ex. PRDT-1399)_  
_이슈 URL을 복사해 붙여넣어도 괜찮습니다._

PRDT-2146

# CheckList

***Reviewr는 아래 체크리스트를 확인해주세요***

(PR 작성자는 체크리스트를 수정하지 마세요)

- [ ] `ooo.stories.ts` 파일에 `title`이 제대로 설정되어 있는가?
- [ ] `ooo.tsx` 파일이 `export default function`을 사용하고 있는가?
- [ ] `ooo.types.ts` 파일에서 MUI type을 적당한 곳에서 잘 import해오고 있는가?
- [ ] `ooo.mdx` 파일에서 `<Controls />`의 `include` prop이 잘 설정되어 있는가?
- [ ] 변경사항 전반적으로 import문을 `index.ts`가 아닌 정확한 파일에서 import하고 있는가?
- [ ] 작업된 컴포넌트를 `src/index.ts`, `src/components/index.ts` 파일에서 export하고 있는가?

# Description

## 요약

_이번 PR의 요약을 적어주세요. 3줄 이내 작성을 권장합니다._

- Divider 컴포넌트를 구현했습니다.

# Reference

_참고문서, 참고링크 등을 적어주세요._

Divider 피그마
https://www.figma.com/file/qfL0NXrfMVNIlBszjy8T8z/ACON-Design-System-(%EA%B3%B5%EC%82%AC%EC%A4%91)?type=design&node-id=1856-3604&mode=design&t=iR49uNbgRVQTZBtK-0

2024-04-12 21:09 UTC, flynn0909 requested changes

2024-04-12 21:09 UTC, flynn0909 commented on src/components/Divider/Divider.types.ts
> +  color: 100 | 200;
다른 곳에서는 color props에 대해 'color/primray/600' 처럼 토큰 전체를 받다가 이 친구는 갑자기 '100' | '200'을 받으니까 어색하게 느껴지는데요.

이 부분은 엘로디님과 상의해보고 수정하는 편이 낫지 않을까요? 애드님 의견은 어떠세요?

2024-04-13 11:45 UTC, add0215 commented on src/components/Divider/Divider.types.ts
> +  color: 100 | 200;
남겨주신 부분을 읽어보니 플린님 말씀처럼 color 토큰의 일부만 넣어주는 것이 더 혼란을 줄 수 있다고 생각되는 것 같습니다!

아래 2가지 방법이 생각나는데, 
- color 토큰을 넣어줄 수 있도록한다.
- 색상은 2가지만 사용하므로 mui의 light 옵션처럼 ture일경우 100, false일 경우 200을 적용하는 옵션을 추가한다.

저는 2가지의 색상으로 유지된다면 2번째 방법을 선택하고 싶은데, 이 부분은 엘로디님과 상의해서 정해보도록 하겠습니다!!

2024-04-15 04:24 UTC, flynn0909 commented on src/components/Divider/Divider.types.ts
> +  light: boolean;
light는 필수일 필요가 없지 않나요?

2024-04-15 04:24 UTC, flynn0909 commented on src/components/Divider/Divider.types.ts
> +  color: 100 | 200;
Good Good 입니다

2024-04-15 04:40 UTC, add0215 commented on src/components/Divider/Divider.types.ts
> +  light: boolean;
light옵션과 함께 orientation도 2개의 값만 존재하므로 옵셔널로 변경 후 기본 값을 지정해주었습니다!

2024-04-15 04:54 UTC, flynn0909 approved these changes

2024-04-15 04:54 UTC, merged